### ISSUE TITLE
Failed to inject gmcl_rekinect: Io(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }

### ISSUE THREAD

**Issue by Voidsen** [WilliamVenner/gmcl_rekinect#2]
i have done everything in the tutorial and installed everything correctly, but in rekinector it says the error above, repeatedly

**Comment by WilliamVenner** [comment]
Can you show me your garrysmod/lua/bin folder?

**Comment by Voidsen** [comment]
the files are at the top
![image_2024-01-23_090617722](https://github.com/WilliamVenner/gmcl_rekinect/assets/136021671/b46dfbe2-0d31-4d23-983f-a2f415559377)

**Comment by Voidsen** [comment]
oh, well i am an idiot. thanks
